name: skupal
description: Skupal Project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.13 #local storage
  percent_indicator: ^4.0.0
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  video_player: ^2.2.18
  retrofit: ^3.0.1+1
  logger: ^1.1.0 #for logging purpose
  flutter_riverpod: ^2.1.1 #state management
  json_annotation: ^4.4.0
  fluttertoast: ^8.0.9
  story_view: ^0.14.0
  dotted_border: ^2.0.0+2 #for dotted border
  background_app_bar: ^2.0.1 #for slivers
  flutter_slidable: ^2.0.0 #for sliding widgets sideways
  provider: ^6.0.3 #provider package
  grouped_list: ^5.1.2 #group our messages on chat screens and more
  intl: ^0.18.0 #format date and more
  fl_country_code_picker: ^0.0.1
  random_string: ^2.3.1
  animate_do: ^3.0.2
  lottie: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: "^6.1.6"

flutter_icons:
  image_path: "assets/middle logo.png"
  android: true
  ios: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/anim/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CerebriSansPro-Regular
      fonts:
        - asset: assets/CerebriSansPro-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
